version: 2
jobs:
  build:
    docker:
    - image: circleci/python
    working_directory: ${CIRCLE_WORKING_DIRECTORY}
    steps:
    - checkout
    - run: ls # run: ${CIRCLE_WORKING_DIRECTORY}\runUnitTests.bat

