version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/workspace
    steps:
      - checkout    
      - run:
          command: |
            sudo pip install pipenv
            sudo pip install pep8
            sudo pip install unittest-xml-reporting
            pipenv install
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            # pipenv run python ./Import/unitTest.py
            python ./Import/unitTest.py
            pipenv run pep8 . --filename=*.py


