version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.2
    working_directory: ~/workspace
    steps:
    - checkout    
    - run:
      command: |
        sudo pip install pep8
        sudo pip install unittest-xml-reporting
        pipenv run python ./Import/unitTest.py
        # pipenv run pep8 . --filename=*.py


